### ISSUE TITLE
Specify the specific API and resource for owners

### ISSUE THREAD

**Issue by sftim** [edixos/Nauticus#32]
# Describe the feature

This should change:

```yaml
...
spec:
  owners:
    - name: dev-team@example.com
      kind: Group
```

A `kind` is not sufficient to definitively identify which API group we mean here. Instead, we should specify owners more like:
```yaml
...
spec:
  owners:
    - name: dev-team@example.com
      apiGroup:  rbac.authorization.k8s.io
      apiResources: groups # yes, the lowercase plural form that you see at the HTTP layer
    - name: bot@example.net
      apiGroup:  some.other.example
      apiResources: externalserviceaccounts # for this example, it could be an aggregated API
    - name: phippy@example.net
      apiGroup:  avatars.some.other.example
      apiResources: users # ambiguous name, disambiguated by API group
```

We also shouldn't assume that Kubernetes RBAC is the only game in town. You can have a conformant Kubernetes cluster that uses a different access control mechanism and runs with RBAC disabled.

# Expected behavior

There's never ambiguity about how we refer to owners.
