### ISSUE TITLE
Space Templates: Provide pre-configured templates for creating spaces that include common resource quotas, network policies, role bindings, etc

### ISSUE THREAD

**Issue by smileisak** [edixos/Nauticus#43]
## Description
The current setup for creating Spaces with Nauticus is straightforward, but often, administrators find themselves repeatedly configuring the same set of parameters, such as resource quotas, network policies, role bindings, etc. This repetition becomes a hindrance to efficiency. To streamline this process and make space creation more efficient, we propose the introduction of Space Templates.

Space Templates would be pre-configured templates that administrators could create, which include common configurations (e.g., resource quotas, network policies, role bindings, etc.).

## Usage
A Space Template could be referenced in the Space resource during creation, and any spec within the Space resource would override the corresponding parameters in the Space Template.

Example:

```yaml
apiVersion: nauticus.io/v1alpha1
kind: Space
metadata:
  name: my-space
spec:
  template: 
    name: my-template
    namespace: nauticus-system
  networkPolicy: 
    .... # This would override the network policy in 'my-space'
```

Here, my-template would be another Kubernetes custom resource of kind SpaceTemplate.

```yaml
apiVersion: nauticus.io/v1alpha1
kind: SpaceTemplate
metadata:
  name: my-template
  namespace: nauticus-system
spec:
  resourceQuota: 
    ...
  networkPolicy: 
    ...
  roleBindings:
    ...
```

## Deliverables

1. Define the SpaceTemplate CRD.
1. Update the Space CRD to reference a SpaceTemplate.
1. Update the Nauticus controller to handle SpaceTemplate references and overrides.
1. Update the documentation to include SpaceTemplate usage.

This feature would greatly streamline the creation of Spaces and improve the efficiency of administrators. I look forward to seeing this implemented!
